logging:
  file:
    path: /Users/zephyr/Desktop/test_workspace/gas
    name: hgf-log
  level:
    root: info



modbus:
  read-requests:
    - start-address: 0x0006
      quantity: 0x008
    - start-address: 0x0380
      quantity: 0x0002
    - start-address: 0x000D
      quantity: 0x0004


mqtt:
  server-url: tcp://mqtt-broker:1883
  client-id: zephyr
  application-id: 4

servers:
  server-list:
    - name: Server1
      host: 172.30.1.233
      port: 5300

spring:
  influxdb:
    url: http://localhost:8086
    user: zephyr
    password: zephyr7419
    org: Musma
    bucket: modbus
    measurement: status
    token: 0FQPbYlJ1rqHKpOyFxEWFn1bJ2VwigmTxJFry25I-zkeCaNIKF0J-xMunZBrHBLTx0H3mlzk09ov93qtOTpCBA==

