version: '3.8'

services:
#  springboot-hgf:
#    image: hyuk12/hgf-springboot:v1
#    container_name: message-collector
#    ports:
#      - "8082:8082"
#    command: ["java", "-jar", "app.jar", "--spring.config.location=file:/config/application.yml"]
#    volumes:
#      - "./application.yml:/config/application.yml"
#      - "./mosquitto/config/ssl/client/client.pem:/mosquitto/config/ssl/client.pem"
#      - "./mosquitto/config/ssl/client/client-key.pem:/mosquitto/config/ssl/client-key.pem"
#      - "./mosquitto/config/ssl/ca.pem:/mosquitto/config/ssl/ca.pem"
#      - "./hosts:/etc/hosts"

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    command: [ "mosquitto", "-c", "/mosquitto/config/mosquitto.conf" ]
    volumes:
      - "./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./mosquitto/config/ssl/server/server.pem:/mosquitto/config/ssl/server/server.pem"
      - "./mosquitto/config/ssl/server/server-key.pem:/mosquitto/config/ssl/server/server-key.pem"
      - "./mosquitto/config/ssl/ca.pem:/mosquitto/config/ssl/ca.pem"
      - "./mosquitto/config/ssl/mosquitto/config/aclfile:/mosquitto/config/ssl/mosquitto/config/aclfile"
