apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: influxdb
  name: influxdb
  namespace: influxdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/name: influxdb
  serviceName: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.2
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influx-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: influxdb
    name: influxdb
    namespace: influxdb
spec:
  clusterIP: None
  ports:
    - name: influxdb
      port: 8086
  selector:
    app.kubernetes.io/name: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: influxdb
  name: influx-nfs-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 30Gi