apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: message-collector
  name: message-collector
  namespace: dsme-gas-fan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: message-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: message-collector
    spec:
      containers:
        - image: hyuk12/hgf-springboot:v1
          name: mqtt-java
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: application-config

---
apiVersion: v1
kind: Service
metadata:
  name: message-collector
  namespace: dsme-gas-fan
spec:
  selector:
    app: message-collector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: dsme-gas-fan
data:
  application.yml: |
    logging:
      file:
        path: /Users/zephyr/Desktop/test_workspace/gas
        name: hgf-log
      level:
        root: info
    modbus:
      read-requests:
        - start-address: 0x0006
          quantity: 0x008
        - start-address: 0x0004
          quantity: 0x0002
        - start-address: 0x000D
          quantity: 0x0004
    mqtt:
      server-url: ssl://mosquitto-customer.dsme-fan.svc.cluster.local:8883
      ca-file: /config/ca.pem
      client-crt-file: /config/client.pem
      client-key-file: /config/client-key.pem
      client-id: zephyr
      application-id: 4
    servers:
      server-list:
        - name: Server1
          host: 172.30.1.233
          port: 5300
    spring:
      influxdb:
        url: http://influxdb2.influxdb:8086
        user: admin
        password: DjeDfSaK92h8eBU
        org: dsme
        bucket: gas-fan
        measurement: status
        token: URM7oW0jpir_ATozOhlTzyJMc15YBp8-Khn9cJYCB1b00tfS1PltvzoPTgcOyRiQyyj3MZCKM0dQB4w8sA==

  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDdjCCAl6gAwIBAgIUNNo692mAQBlb42tvjG11Us1S9QowDQYJKoZIhvcNAQEL
    BQAwUzELMAkGA1UEBhMCS1IxDjAMBgNVBAgTBUJ1c2FuMRQwEgYDVQQHEwtIYWV1
    bmRhZS1ndTEOMAwGA1UEChMFTXVzbWExDjAMBgNVBAMTBU11c21hMB4XDTIyMDIy
    NTAxMzMwMFoXDTI3MDIyNDAxMzMwMFowUzELMAkGA1UEBhMCS1IxDjAMBgNVBAgT
    BUJ1c2FuMRQwEgYDVQQHEwtIYWV1bmRhZS1ndTEOMAwGA1UEChMFTXVzbWExDjAM
    BgNVBAMTBU11c21hMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxuT4
    63E8vnW7JapImVnAJcNZbIH3BL2SZhWmeQk99JFG3Lrt+Uee17/sHW+2/raZQHJ4
    EiwzUpSPxjA8n93zUkkMSta+UQqeHpyng1fHmijH7T6prDFTKSI1f04BxOx0NQ5H
    UGo7SNb/ZG48Ci8dTWFmf2Hd/4sCHpAVKwWWNle7YKSne8Pnba5JiUjYb5MyQw3X
    AiQCf9NVW5TEOGdOPLdvVxLaqJZmcobJ3hMwrJaR0Po5RXOY/ZaJv3+zzSz1Fmz+
    FU9mJ9sX9eX3+T4UAXQ+qwaH/NjLYnoIemvgiMGfHq3eF5FnD66yV8+PaFqGVBHa
    tijSXZlhr4x2MRfugQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQURDVFPi+V8RXzStFghv66gsKkJG8wDQYJKoZIhvcN
    AQELBQADggEBAHn03i+5R2bg/xu+Hq/tFrAAK6E/rfqy9G6bz9DpOv+rzVQrH2f1
    6hVyN6xDJ4Gp5O92CRbMDM5+139mlj89izMRvw+bVoowBM4DvD+G4zBWqPaspfY4
    N8I2h9kNgdou6SbonVtZJFLSyOMrrAgseC8ZrdkfrkvkHbKDLmTKaS3duzyajLWk
    6fvAzZ951ODnVGmjQrybaUd66tfkNgSJgXX5Ou0wMdriNRs9SRpBYPkQkXAuVGez
    XVvH5xSRKUJHhbN90hD3i+4sxgtCN7S63aE+HzPiFF37J9ZvrB89AZeqoqJaLdqw
    UWqy7fRvRPxvNebl/fwvYKJd/F4tLKyWKZA=
    -----END CERTIFICATE-----
    
  client.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDZzCCAk+gAwIBAgIUSSwjAnKp5knGMNt7OoNg5o/D+vwwDQYJKoZIhvcNAQEL
    BQAwUzELMAkGA1UEBhMCS1IxDjAMBgNVBAgTBUJ1c2FuMRQwEgYDVQQHEwtIYWV1
    bmRhZS1ndTEOMAwGA1UEChMFTXVzbWExDjAMBgNVBAMTBU11c21hMB4XDTIzMTAx
    MzAyNDQwMFoXDTMzMTAxMDAyNDQwMFowETEPMA0GA1UEAxMGemVwaHlyMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnU59uTCjIN7C10uYTg0LI/q8j6+F
    Yps+rUnAPAdarrTI4KJeKycNUhTASMdJkes3dyG9ijF33tRGBOSKP2nwc4t/rMnm
    MVzcOaYDvznen+8K6cYKw8kT2R80fkQpzLETr6Ib9CGOQmiih1BY0kjhB6KIlBbv
    MjmYlDj62ZZ26PPVZalmdKuP6LlUz0Z3vH2c9aB0Y5mwh1C3idbtyeO3wFkM8IbN
    gIBX5yDS2vjcvofTNPuAylDJZqtI6qsYkDIwGtpccEBXqFLLIqmgQZ6iiifE8hsp
    xnAzm9fbJPpe1FI7fIwPeaLUqPtl68zxFanXQg5Yt/VQEyndrGrI8zx+/QIDAQAB
    o3UwczAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYDVR0T
    AQH/BAIwADAdBgNVHQ4EFgQUzNEPzBqIGiWIsULWL4z0XEG8ftgwHwYDVR0jBBgw
    FoAURDVFPi+V8RXzStFghv66gsKkJG8wDQYJKoZIhvcNAQELBQADggEBAH8bF8Kn
    5dCSVA6xtoBnkUHJWHS39qMtKxC1FoZQmIGOwwh3xNH9KTmLotgH39Q7v2arZJRj
    gb7Wlh5pK/WQFpM7u3hE5nSXa3Aig+Vy4PxG36v/1i0f6SxDtKY9tDz+ewz8jqek
    ByQaZJAg5WBq2DUTejehMHa7Zl4sYweuj/RF9kBt2ZK9mvhYopnVvB3+pOmCXVRA
    5vLoqBEtNgVrSHK1ccWFVMIt/mKy7dpAS3IbAafI5BlMW/rVg3dmGA9UgCCbCCA5
    PYcqVkcBnK8dbifkd54svbGTtQUc9+cQH7QWGFGiqJxmriyEFzwP8HqV94Zg8t5m
    HOgWo7Ea3nuclpw=
    -----END CERTIFICATE-----
    
  client-key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAnU59uTCjIN7C10uYTg0LI/q8j6+FYps+rUnAPAdarrTI4KJe
    KycNUhTASMdJkes3dyG9ijF33tRGBOSKP2nwc4t/rMnmMVzcOaYDvznen+8K6cYK
    w8kT2R80fkQpzLETr6Ib9CGOQmiih1BY0kjhB6KIlBbvMjmYlDj62ZZ26PPVZalm
    dKuP6LlUz0Z3vH2c9aB0Y5mwh1C3idbtyeO3wFkM8IbNgIBX5yDS2vjcvofTNPuA
    ylDJZqtI6qsYkDIwGtpccEBXqFLLIqmgQZ6iiifE8hspxnAzm9fbJPpe1FI7fIwP
    eaLUqPtl68zxFanXQg5Yt/VQEyndrGrI8zx+/QIDAQABAoIBAChmwGOP2lXW4LPq
    9nMVZocXHtbIfbmVpcNb7cN9IA0+4VjQWt86aHFsYvZOONcBUn2GbOfRTLguTM10
    5QzkaJ1EdsYqFLUY5Hbp7IxwkH0DKApikuE2A6MAILtNRm8MC8JQIF3TQHZN6XBX
    cniPvzv2wp1GRqjfohBvkf3QZzns/wlI5/GlCfoS6SmLcA/HoyWAyEhJqivG4n5B
    spzuzYE4V6JLyRqrjK6Okn/U2BITpiDO464oPgv+mna3vpHsg7L8uu5PFo9Y3biO
    ydGqn0Q6QxlLYy1lZorgHy1D5GJam/7Zoa/6Lx9ECk5ooeGPU8BqIHQDJpgyg99h
    7sAysAECgYEAzBywjyMQOjsaKnYnzfCQbQhjlj9AeOc84y1ovGO3+0M4K3yxQFfB
    PF5Gta1ePvOh19bRSuq4czbGUr+ipRHytEOh8qfDxFR0Vye+kOabc9LqtwyFRifK
    lcG7jkOu74nZa37XPYZjN+3eeRMD9UZIkSaIqJnb1NeQqBkn/LEFjfECgYEAxUvF
    efTwFe9fXAtsJQCdkY1MuArEftfJoqPpEcjyonNOQHBgFdJJs/V03bBplWneUDpR
    E9mSzCU89GI9LUMwjdsbfJijb9KpNHH3rYYEYpDjZDsF4chfOs5UHfQ6nmewUgmL
    cXBkILlciUfzE/1an2tfOeE1TgqMINypwvqmJc0CgYEAkGYLknff1xJQ5JFKf6sc
    wcYZjgWZeu88aAuL+Rsi4aMgbcN9MmPi1O5tX8IS1r5NVQEod7OuYfPyQkBItDcK
    WPUv8Rc2rAKDe9UmQCSk/T/NxUoaTxN/gorYQUEo1VXUdvP5GhGkx8CEj2sgdbkP
    RYDZVU3j86O9Nu71FxO1NkECgYBUlCIJIT7XOHH55I+s4TGrVxa/gyYvdlRjW78r
    t6iEicfPCh223Rppgl1iOCFbQzJh1E4zoz8yMviJj5/ISpiDB54l8M2Hv5h3+i+C
    fQReONyyeDcSTrK8Y/1dhfinNa45zQuxSswx1yTbWTPUqvTxiLce+fO/C/h8kfxY
    sNkPNQKBgQCL+P7hbOI6UH/OVMi6XV839VZ/nyg2eJfTU51PMEPv0OMx8M5uIVlF
    rIVby8lbqQz8dnfB/q1bYWTBlu9Pcp7QAn9oirU+qFVmH+QfUUcMZNUBp3IXRoaX
    KRprpf2tk8Vy9LoCcNHUHxjJhHnpB6IC8+O6sDk8bYGHvwdzqrPGVA==
    -----END RSA PRIVATE KEY-----


#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: message-collector
#  namespace: dsme-gas-fan
#data:
#  cafile: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkakNDQWw2Z0F3SUJBZ0lVYmRyd1hDVE9RRytrYjBMcG1kdVhvZ0xXNFNrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1V6RUxNQWtHQTFVRUJoTUNTMUl4RGpBTUJnTlZCQWdUQlVKMWMyRnVNUlF3RWdZRFZRUUhFd3RJWVdWMQpibVJoWlMxbmRURU9NQXdHQTFVRUNoTUZUWFZ6YldFeERqQU1CZ05WQkFNVEJVMTFjMjFoTUI0WERUSXhNREl3Ck1qQTBNRGN3TUZvWERUSTJNREl3TVRBME1EY3dNRm93VXpFTE1Ba0dBMVVFQmhNQ1MxSXhEakFNQmdOVkJBZ1QKQlVKMWMyRnVNUlF3RWdZRFZRUUhFd3RJWVdWMWJtUmhaUzFuZFRFT01Bd0dBMVVFQ2hNRlRYVnpiV0V4RGpBTQpCZ05WQkFNVEJVMTFjMjFoTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFuMUJsCnhVTHR6VE5kNkE0Q2NaTG5FbmJtSGNSWkJ0VGJLMzlZbHdkQ2VrS3FTdlhPRnhSd0JHV0lEcFVXZ20zRDRNMHUKVUxXRTYrSDRtMDhqeDlLTXB4U1VaajNPeUpRNXpya29sVjhCS2FCbjR4cUNTRExzOThsNFVVRVc1am9hZlNaNgo2akZtdWVKRUdUcURsT01vRG9pYm9vVnFQUStyTVkvaVF0RyttbnZpeGRWUnFNcHNGSkVIT3dxVVVIYWNweGdlClJOM0UvNm4zLzErejhsMmw0Y2JPYnRLR0k2OFp6VnMwMVJOZkphRWxGME5vSWVGa1pBbGdHME91MWNCTlBLa1kKNWNoQXppbGVNWGJWVzdLT1pkOGtTMTZ0dm8rMjRSWHhVVUdUYk10Y2RManUvcHcrcmFpbHFqOU5NWFpSWjVCaQp3c1dUSldrck9ZUmtUTjhQNlFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXo5dzdGUnB4d3M1WUluNTlHa0NYU0JCQWlBSXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUJNWnFWQVFHcFFGRDY4dWc4UkYzVmtteThuWXpzcUNUNGdnbm4wRjFNb21GVzU5SUx1SwpYenc2K2pjeVk0TmFHSEd1U3N0QmdxM2t3NER3dk5SZTYzeUU1YU1aUlhDS2tLSmlOcWtIejZWV1FjWXpFckpHCmFvM1dYSGxWbDZmVGhWUzFBU3NJMlgxanFsOXkyZGEwTXliaUs0eDd0MG1EWXRXclFQdzhFZHBOYk5SaWx5alkKdXU5RjdmdGhmaWZRY3hJYTYrdWxyNWExUFJoSWd2VWszcDlNaFNRTVh6QWppRDZyM3g2TzlTRVRSUUx6T0orQwo2Z0hBc0VaMlBMSGRmb2dNanZFLzFUaEw4TzByMDZIMzQ3WTZ5NG9PeXVnK2dYOVlUVjcyQlI5NnFza1lCc0ZoClk1NUJQRHFXRzk4aXhZOXRDM0QzQXBPbEMvSmJzaGVjTnVBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#  certfile: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjakNDQWxxZ0F3SUJBZ0lVTHNOYXZTUmFEWGpHQlc3NnpKOFFkSDdFWExvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1V6RUxNQWtHQTFVRUJoTUNTMUl4RGpBTUJnTlZCQWdUQlVKMWMyRnVNUlF3RWdZRFZRUUhFd3RJWVdWMQpibVJoWlMxbmRURU9NQXdHQTFVRUNoTUZUWFZ6YldFeERqQU1CZ05WQkFNVEJVMTFjMjFoTUI0WERUSXhNRGN3Ck5qQTROVGd3TUZvWERUSXlNRGN3TmpBNE5UZ3dNRm93SERFYU1CZ0dBMVVFQXhNUmJXVnpjMkZuWlMxamIyeHMKWldOMGIzSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDZGZrWkorQmkyS0JjWApDRDlZME9hWDhVblJnelM1eDdCWXNVWnNkN01TSDRGRno3RCtpajFzZCs1b3BkZ1R6VmFYcFVId3liNFJnUjVHCjZHV0hKN2hxZTZUcjRJb09MV2VyYVZSZEhCbm1lWXpuYndIZ3dWWGZtU2N2cUFiZkxuSjhkNC9Fa0dsV2Z1RUYKMnBqNXdMWnUxSjFLd0lTM1o1TTh6ejl1Si96VmR6SXBmR3ZISjliT2xFMkhHR1FZejV5ZUJNbE9MUk4wNjlPbQpkb21CNGRmakg2eEczS3gzL1BlQkM3dWY2RVJSRmtNU3orcWFDZ1FHMVp2SkgrMXVROUI2aFpBOVVVazBXdzcrCi8vbGFyT3VhcSs0K3FrMlJJUkpwSkhZYUcvQW4yd2g4TnQwclNVQXVCK0xjUmpOVG9wUXRXZk5mUm9VaVJnc0kKaEJaOW1ZTi9BZ01CQUFHamRUQnpNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlNNa0hlbU1Ic2tmaDllUmNka1I4Ym8wTm5aCmpqQWZCZ05WSFNNRUdEQVdnQlRQM0RzVkduSEN6bGdpZm4wYVFKZElFRUNJQWpBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFnYVdtbUdwbVVPenE0Tm5yS3hPRDBWNUtVNjhod2J3KzF1MjFobm5qb2JtNThhbkhicjNHN0pjTgo1Y0h4MHdtdUFQZ3R5RWM1UUxNZXVDSFM0NUZFUExkc3VPQ2hlNWtaUzdPc1h2SE5zVzIzbitIak92UUo3VVpMCmN4TVM5S01WYU45alpBUXZGaS9iZWVoakhob2dPejRhcFBDQ0VSRnRqeEl5TzFlV3U5KzRUUmdHbTdiQTFSdkYKMk9TRnVyamd3UDRXZGJFeW90YnVlMFVwa3JacTNsaW5KbnA2QklJSG1KZWVOVkpuQzdyRGJBTjZXMktSbHlINApEVmVvdGYyc2pESlhBR3hCL3NudlNuVUZYSmFQaXZteUd5WE1SRFdrZlc0Y0JNSmRuUFhOOTN3WDd3V3ZNSHBhCkRHckE3cG1meXNxaG1mRXZQSFJqNlpEVm9iSkV4UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#  keyfile: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBblg1R1NmZ1l0aWdYRndnL1dORG1sL0ZKMFlNMHVjZXdXTEZHYkhlekVoK0JSYyt3Ci9vbzliSGZ1YUtYWUU4MVdsNlZCOE1tK0VZRWVSdWhsaHllNGFudWs2K0NLRGkxbnEybFVYUndaNW5tTTUyOEIKNE1GVjM1a25MNmdHM3k1eWZIZVB4SkJwVm43aEJkcVkrY0MyYnRTZFNzQ0V0MmVUUE04L2JpZjgxWGN5S1h4cgp4eWZXenBSTmh4aGtHTStjbmdUSlRpMFRkT3ZUcG5hSmdlSFg0eCtzUnR5c2QvejNnUXU3bitoRVVSWkRFcy9xCm1nb0VCdFdieVIvdGJrUFFlb1dRUFZGSk5Gc08vdi81V3F6cm1xdnVQcXBOa1NFU2FTUjJHaHZ3SjlzSWZEYmQKSzBsQUxnZmkzRVl6VTZLVUxWbnpYMGFGSWtZTENJUVdmWm1EZndJREFRQUJBb0lCQUdCMnNIeXI3ZzdjUFZCSgpKK3V4Z0J1K21YVXZSUU1wY1RUUjJBMmx2MU94WWsrdEozNndrM0MxZ0p3dVFFdllzRm9QeVhTL1RLQ1NFa1ppCkg1V0oyYVcyOTh2VjZ4bEY3RUtNTURVYmVpMjFjMzFwZTUvN0t5cmFOcXMwNG9pZWZWY0pNRkM0Rnh6NGQ4RkwKSS9tTmRQQXJYL0FpUE9mTkU5emlIN3JMMlV1eFVWT0d5bm9pTDNib0tQeFpkaVZEOTZuR1hHejB6OCtvTU1jVwpPQkw1SzFldWNSakxrcWR1UjZxcEhiR1daMFFkclpiVEoxbUt5SjdOeDZoNkV0VGFjYS9uMG90MXZET293azZxClZMazI2RTNweldoSmdvVU5tNjd3bVVUNVNWOXpoQjhOcnkyWXJIRXRGWGxlQjdOSlBzcTRSZU45YTNCbUVZZ0sKeDlYK25GRUNnWUVBeGZ1bUgyK29UcHY4TWt5eU4wUHFGU2VlTnl5aUFRdEtOT1A1Zkh0dDFvSzJlcE45WU02dApnSGtqTkxJUHlwU2hZTkRKM3pUVWlDTStpblgyV0Z1YmZvNWhWVmJjakhxeTBCV1BJNzk2czExSVF2cDRIVnUxClNja1B2THJGT2YwdWdBTXpUa0d6ZlNqYnhJL1VtckN6TXNaVVpOR3lRR0pOcFZ0dklHMVFqMWtDZ1lFQXk2VW4KUXNOamlZcnVlL0pDbVNGSkttUUFXY1ZYaVdOOVlWeVFJQURqOFF0emMxc1FtYmpnMitrdXpIY09yREVZYXdWRgo0NFRHMjhQUWs4TTYyMmVWelhqTkE3N2h0K24vd2g3STNnQi93UmI2RXdweXVVSUtsRWdSdzN2SFptL0diQk9NCmZxK3Rsb1RTUjh6MTFXc29XMU1yQnZzelRIL3VMa3NEUlU1RDVwY0NnWUVBay9zQmN6UEpNR0NGQTYreDhYN3cKd3prbW1BVGpYalpyRTlkbWpqWFBwbXR6SzNGOFlGUjYrTEVTc0h0N05DY2Q3RGlDK3pRSXUyemtmU2VvcHVocAo5QkZHRFR4c2d3L2ZBWXRydndPTEdlL2FhRDNBYytrdE91WnV2ZGs0TzV6VEdkbktpbTZ2VXhpc0UyS1NQY0ZmClg4OUFHMDlsbFp3a2Z6azFlWjViZlprQ2dZRUFuTDF1N0hvS3dMQ0lRaW9Dakc0TUxHNXZ2cWlmYVlXRDJVNHYKT0JLM1hxM2JuR3Y0NlBoZFNhVytlVzBoZy9MOXdsRjZxMVZrNFgxanFuZFhjOHZVaHlOMVdHNnd1S2VJVE5iNAo3N1llbm5XYTRORG40Q011bFZhckpYUzkwdUF4THJvVkp1VDhqSitLWWUwbFFiQ0tqVkFFREFtSVFGY3U4YjZXCnM5ODdiOTBDZ1lFQXQwVEVsYTk0azIrbDFFdUpZeTMrMVcrVEJPdTVhQTNMdDl3TmZQcVpTWHVDdTBVNTNlV3kKUGhNSjZhTUs0WHdqWGxzcDNjSFJUa1hITFBRRUZ6RUE4T1gyUFgrRkk0RVJoNVZPVjZoaG1NbWc2cmovdTZOSgpRV3IxaFlpWmQyS2pVRVg3TU1Vcmc4UHU1UWp3bHpFdldEZFgvSUxCN1RRTEQxTmgxc1NBOFljPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
